apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: echo-server
  externalTrafficPolicy: Local
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echo-server
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo-server
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 10