apiVersion: apps/v1
kind: Deployment
metadata:
  name: restrict-scale-down
  labels:
    spotinst.io/restrict-scale-down: "true" 
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
        containers:
        - name: nginx-od
          image: nginx
          resources:
            requests:
              memory: "700Mi"
              cpu: "256m"