apiVersion: apps/v1
kind: Deployment
metadata:
  name: r3.large-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-in-r3-large
        image: nginx
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1700Mi"
            cpu: "1700m" 
      nodeSelector:
        beta.kubernetes.io/instance-type : r3.large