apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-test-nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-env-test-container
        image: nginx
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "1700Mi"
            cpu: "1700m" 
      nodeSelector:
        env: test