apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-lifecycle-spot
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
        containers:
        - name: nginx-spot
          image: nginx
          resources:
            requests:
              memory: "700Mi"
              cpu: "256m"
        nodeSelector:
          spotinst.io/node-lifecycle: spot