apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-lifecycle-spot
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
        containers:
        - name: nginx-spot
          image: nginx
          resources:
            requests:
              memory: "700Mi"
              cpu: "256m"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: spotinst.io/node-lifecycle
                  operator: In 
                  values:
                  - spot